/**
 * DO NOT EDIT THIS FILE
 *
 * Generated from the rules' `meta.docs.preset`. Run `pnpm update-rule-configs` to update it.
 */

import type { ESLint, Linter } from 'eslint';
import { buildPreset } from './build.js';

export default (plugin: ESLint.Plugin): Linter.Config[] =>
  buildPreset(plugin, 'lite', {
    'class-member-order': 'warn',
    'comment-style': 'warn',
    'decorator-order': 'warn',
    'no-commented-out-code': 'warn',
    'no-llm-artifacts': 'warn',
    'no-stray-semicolon': 'warn',
    'one-line-guard': 'warn',
    'statement-spacing': 'warn',
  });
