/**
 * DO NOT EDIT THIS FILE
 *
 * Generated from the rules' `meta.docs.preset`. Run `pnpm update-rule-configs` to update it.
 */

import type { ESLint, Linter } from 'eslint';
import { buildPreset } from './build.js';

export default (plugin: ESLint.Plugin): Linter.Config[] =>
  buildPreset(plugin, 'recommended', {
    'class-member-order': 'warn',
    'comment-style': 'warn',
    'decorator-order': 'warn',
    'file-suffix': 'warn',
    'max-comment-lines': 'warn',
    'max-dependencies': 'warn',
    'max-params': 'warn',
    'max-public-methods': 'warn',
    'no-comment-semicolon': 'warn',
    'no-commented-out-code': 'warn',
    'no-filler-comments': 'warn',
    'no-llm-artifacts': 'warn',
    'no-new-service': 'warn',
    'no-restating-comment': 'warn',
    'no-restating-jsdoc': 'warn',
    'no-stray-semicolon': 'warn',
    'one-line-guard': 'warn',
    'prefer-http-resource': 'warn',
    'prefer-service-decorator': 'warn',
    'statement-spacing': 'warn',
  });
