import { PRESETS } from '../src/utils/create-rule.js';
import { emit, finish, ruleEntries } from './shared.js';

const SEVERITY = 'warn';
const DISCLAIMER = `/**
 * DO NOT EDIT THIS FILE
 *
 * Generated from the rules' \`meta.docs.preset\`. Run \`pnpm update-rule-configs\` to update it.
 */`;
const entries = ruleEntries();

for (const preset of PRESETS) {
  const rules = entries
    .filter((entry) => entry.presets.includes(preset))
    .map((entry) => `'${entry.name}': '${SEVERITY}',`)
    .join('\n');
  await emit(
    `src/configs/${preset}.ts`,
    `${DISCLAIMER}

import type { ESLint, Linter } from 'eslint';
import { buildPreset } from './build.js';

export default (plugin: ESLint.Plugin): Linter.Config[] =>
  buildPreset(plugin, '${preset}', {
    ${rules}
  });
`,
    'typescript',
  );
}

finish('update-rule-configs');
